version: '3'

services:
    app:
        build: .
        networks:
            - app
        environment:
            DATABASE_URL: root:root@tcp(database:3306)/go_gin?parseTime=true
        depends_on:
            database:
                condition: service_healthy
        ports:
            - '8080:8080'

    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go_http
        volumes:
            - go_gin_database:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/local/bin/healthcheck.sh',
                    '--su-mysql',
                    '--connect',
                    '--innodb_initialized',
                ]
        networks:
            - app
        ports:
            - '3308:3306'

volumes:
    go_gin_database:

networks:
    app:
